services:
  angular:
    image: angular:17
    ports:
      - "4200:4200"
      - "3000:3000"
    volumes:
      - .:/app
    working_dir: /app
    command: ng serve --host 0.0.0.0 --disable-host-check
